### ISSUE TITLE
TypeError: null is not an object (evaluating 'RCTVideoInstance.Constants')

### ISSUE THREAD

**Issue by domene96** [TheWidlarzGroup/react-native-video#1738]
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s, the componentWillUnmount method, 
    in Cpi (at SceneView.js:9)
    in SceneView (at StackViewLayout.tsx:910)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.tsx:106)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:71)
    in Screen (at StackViewCard.tsx:93)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:982)
    in RCTView (at View.js:45)
    in View (at screens.native.js:101)
    in ScreenContainer (at StackViewLayout.tsx:394)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewLayout.tsx:384)
    in PanGestureHandler (at StackViewLayout.tsx:377)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.tsx:103)
    in RCTView (at View.js:45)
    in View (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:40)
    in StackView (at createNavigator.js:81)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at createAppContainer.js:430)
- node_modules/expo/build/environment/muteWarnings.fx.js:26:24 in error
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:638:36 in warningWithoutStack
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:16356:6 in warnAboutUpdateOnUnmounted
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17937:37 in scheduleWork
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:6934:17 in enqueueSetState
- node_modules/react/cjs/react.development.js:325:31 in setState
* tabs/Cpi.js:72:20 in <unknown>
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:25 in <unknown>
- ... 8 more stack frames from framework internals

TypeError: TypeError: null is not an object (evaluating 'RCTVideoInstance.Constants')
- node_modules/react-native-video/Video.js:264:42 in render
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:11581:21 in finishClassComponent
- ... 16 more stack frames from framework internals

This happens for many different implementations of <Video>, <VideoPlayer> and more.

**Comment by domene96** [comment]
`import React, {Component} from 'react';
import {Text, View, Button, Image, StyleSheet, Platform, NetInfo, Alert} from 'react-native';
import Video from 'react-native-video';
import allStyles from '../css/allStylesCSS.js';
import Menu from './Menu';
import Rabbit from '../rabbit.mp4';
// import MediaControls, { PLAYER_STATES } from 'react-native-media-controls';

export default class VideoComponent extends React.Component {
  render () {
    return (
      <View style={{position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, justifyContent: 'center', alignItems: 'center', zIndex: 9,}}>
        <Video
          source={ Rabbit }
          ref={(ref) => {
            this.player = ref
          }}                                      // Store reference
          onBuffer={this.onBuffer}                // Callback when remote video is buffering
          onError={this.videoError}               // Callback when video cannot be loaded
          style={styles.backgroundVideo}
          resizeMode={"cover"}
        />
      </View>
    )
  }
}

const styles = StyleSheet.create({
  backgroundVideo: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0
  }
});`

**Comment by CHaNGeTe** [comment]
You have a problem linking the library

**Comment by CHaNGeTe** [comment]
https://github.com/react-native-community/react-native-video/issues/1502

**Comment by domene96** [comment]
I have linked it
![Captura de Pantalla 2019-09-03 a la(s) 14 41 35](https://user-images.githubusercontent.com/12516433/64203410-f38c1a80-ce58-11e9-8ade-01bdc0fd9af2.png)

**Comment by CHaNGeTe** [comment]
ios or android? lib version?

**Comment by domene96** [comment]
package.json
`{
  "main": "node_modules/expo/AppEntry.js",
  "name": "Chinatown",
  "version": "0.1.01",
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^34.0.4",
    "firebase": "^6.5.0",
    "react": "16.9.0",
    "react-dom": "^16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz",
    "react-native-communications": "^2.2.1",
    "react-native-datepicker": "^1.7.2",
    "react-native-easy-grid": "^0.2.2",
    "react-native-fast-image": "^7.0.2",
    "react-native-fcm": "^16.2.4",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-image-zoom-viewer": "^2.2.26",
    "react-native-lightbox": "^0.8.0",
    "react-native-live-stream": "^1.0.1",
    "react-native-media-controls": "^1.1.1",
    "react-native-reanimated": "^1.1.0",
    "react-native-video": "^5.0.0",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.0",
    "react-navigation-stack": "^1.5.1",
    "uuid": "^3.3.3"
  },
  "devDependencies": {
    "babel-preset-expo": "^6.0.0"
  }
}
`



I'm having this particular issue on android but on ios I'm having a very similar error: null is not an object (evaluating 'RNFIRMessaging.setNotifications...')

**Comment by sourabhmodi20051** [comment]
This can happen if the device/simulator has an old build. Try uninstalling the app from device/simulator and install using xcode. That should resolve the issue

**Comment by CHaNGeTe** [comment]
RNFIRMessaging.setNotifications is not from this lib, is from Firebase AFAIK

**Comment by SupriyaGo** [comment]
Having the same issue, cant able to resolve. please help.

**Comment by techtunix** [comment]
After doing `react-native link react-native-video` 
instead of `import Video from 'react-native-video'; `
do it, like this
`import Video from 'react-native';`
Then, either you got it fixed or jump into next level of 'Games of Bugs' of RN!

**Comment by SupriyaGo** [comment]
still not working
![Screenshot_1575615422](https://user-images.githubusercontent.com/40319687/70302892-3547ab00-1824-11ea-908d-5e75fff7425a.png)

**Comment by TomWrd** [comment]
I stumbled across a solution after struggling with this - none of the suggestions I had run into were working, including running react-native link, restarting the simulator or using the expo video component.  Finally I came across:

https://docs.expo.io/versions/v36.0.0/sdk/video/

If all suggested methods are failing for react-native-video, I suggest working with expo-av.  

run npm install --save expo-av

```
import { Video } from 'expo-av';
export default class YourClass extends Component {
    render() {
        return (
            <View>
                <Video
                source={{ uri: 'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4' }}
                rate={1.0}
                volume={1.0}
                isMuted={false}
                resizeMode="cover"
                shouldPlay
                isLooping
                style={{ width: 300, height: 300 }}
                /> 
           </View>
        );
    }
}

**Comment by yongqicloud** [comment]
hi,Have you solved this problem?

**Comment by hamoody-omar** [comment]
@domene96 I am having the same issue, were you able to solve this problem?

**Comment by hamoody-omar** [comment]
@domene96  I am having the same issue, were you able to solve this problem?

**Comment by IronYR** [comment]
@domene96 same issue. Were you able to solve it?

**Comment by amitbravo** [comment]
> I stumbled across a solution after struggling with this - none of the suggestions I had run into were working, including running react-native link, restarting the simulator or using the expo video component. Finally I came across:
> 
> https://docs.expo.io/versions/v36.0.0/sdk/video/
> 
> If all suggested methods are failing for react-native-video, I suggest working with expo-av.
> 
> run npm install --save expo-av
> 
> ```
> import { Video } from 'expo-av';
> export default class YourClass extends Component {
>     render() {
>         return (
>             <View>
>                 <Video
>                 source={{ uri: 'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4' }}
>                 rate={1.0}
>                 volume={1.0}
>                 isMuted={false}
>                 resizeMode="cover"
>                 shouldPlay
>                 isLooping
>                 style={{ width: 300, height: 300 }}
>                 /> 
>            </View>
>         );
>     }
> }
> ```

is this going to work well with vanila react native project ?

**Comment by FurkanSelvi** [comment]
I'm not using expo, I'm getting the same error is there any solution?, its work IOS but android doesn't work.

**Comment by SalikSayyed** [comment]
I am using Expo still getting this error? but this looks closed is it resolved?

**Comment by sureshiosdevhm** [comment]
Why this issue is closed? Still getting the error.

**Comment by stardollarstar** [comment]
a

**Comment by Jisoonoo** [comment]
so after 2 hours of debugging doing some random things..... I found a solution. This project uses some kind of old Git and gradle can't get it without jcenter().

Anyways, add jcenter() in allProjects to your build.gradle (not APP build.gradle) and npx react-native run-android (rebuild)

![image](https://user-images.githubusercontent.com/45225030/143676752-f50b4cd1-a436-44ed-8bc6-852fd0dd401d.png)

**Comment by cryptic-dev** [comment]
same issue

**Comment by navidabasi** [comment]
> 

This actually worked for me and change the error to:
[Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

**Comment by ShravanMeena** [comment]
> so after 2 hours of debugging doing some random things..... I found a solution. This project uses some kind of old Git and gradle can't get it without jcenter().
> 
> Anyways, add jcenter() in allProjects to your build.gradle (not APP build.gradle) and npx react-native run-android (rebuild)
> 
> ![image](https://user-images.githubusercontent.com/45225030/143676752-f50b4cd1-a436-44ed-8bc6-852fd0dd401d.png)

work for me

**Comment by specter1997** [comment]
> still not working ![Screenshot_1575615422](https://user-images.githubusercontent.com/40319687/70302892-3547ab00-1824-11ea-908d-5e75fff7425a.png)
do you get the solution??

**Comment by YASH6004** [comment]
> > so after 2 hours of debugging doing some random things..... I found a solution. This project uses some kind of old Git and gradle can't get it without jcenter().
> > Anyways, add jcenter() in allProjects to your build.gradle (not APP build.gradle) and npx react-native run-android (rebuild)
> > ![image](https://user-images.githubusercontent.com/45225030/143676752-f50b4cd1-a436-44ed-8bc6-852fd0dd401d.png)
> 
> work for me

It worked

**Comment by specter1997** [comment]
Yes

**Comment by azeezWebsultanate** [comment]
<img width="442" alt="Screenshot 2022-05-31 at 7 11 30 PM" src="https://user-images.githubusercontent.com/87024456/171348451-92dfffb9-367e-4c66-b9d7-25a4de326c7c.png">

Still getting the same error. I have tried everything. Uninstalling from Xcode and then re-install not working for me. The pod installs not working. Linked manually not working.

**Comment by DillonMercz** [comment]
> I stumbled across a solution after struggling with this - none of the suggestions I had run into were working, including running react-native link, restarting the simulator or using the expo video component. Finally I came across:
> 
> https://docs.expo.io/versions/v36.0.0/sdk/video/
> 
> If all suggested methods are failing for react-native-video, I suggest working with expo-av.
> 
> run npm install --save expo-av
> 
> ```
> import { Video } from 'expo-av';
> export default class YourClass extends Component {
>     render() {
>         return (
>             <View>
>                 <Video
>                 source={{ uri: 'http://d23dyxeqlo5psv.cloudfront.net/big_buck_bunny.mp4' }}
>                 rate={1.0}
>                 volume={1.0}
>                 isMuted={false}
>                 resizeMode="cover"
>                 shouldPlay
>                 isLooping
>                 style={{ width: 300, height: 300 }}
>                 /> 
>            </View>
>         );
>     }
> }
> ```

LifeSaver!!!! This solution works very well when no other solution worked. 1 million thanks!

**Comment by anilkumawatparasme** [comment]
i am facing same error

**Comment by ArronJLinton** [comment]
> This can happen if the device/simulator has an old build. Try uninstalling the app from device/simulator and install using xcode. That should resolve the issue

This worked for me. Classic rinse and repeat.

For reference:
```
"react-native": "0.74.3",
"react-native-video": "^5.2.1",
```
