### ISSUE TITLE
onLoad method return wrong naturalSize and I can not get correct orientation of video

### ISSUE THREAD

**Issue by zhuliminl** [TheWidlarzGroup/react-native-video#1859]
```
  onVideoLoad = (payload) => {
    console.log('payload', payload)
    const { naturalSize = {} } = payload
    // const isLandscape = naturalSize.height < naturalSize.width 
    const isLandscape = naturalSize.orientation === 'landscape'
    
    const video = {
      isLandscape
    }
    this.props.updateVideoListIsLandscape(video)
  }
```

**Comment by hokasan** [comment]
I have the same issue. Im using a video recorded on my phone.

**Comment by hokasan** [comment]
Same problem on both iOS and Android.

**Comment by Mussabaheen** [comment]
@zhuliminl  any solution?

**Comment by metizror** [comment]
I have the same issue.
After Trimming Video onLoad method returns wrong orientation 
Any Solution?

**Comment by zhuliminl** [comment]
> @zhuliminl any solution?

just be sure know video size when  you get video uri.

**Comment by freeboub** [comment]
To be tripple checked

**Comment by DwCleb** [comment]
Still without solution?

**Comment by freeboub** [comment]
to bypass this issue we need to add a new notification onAspectRatioChange. it will throw when a new resolution is detected.

**Comment by freeboub** [comment]
This is done on V6.0.0, let's close this issue

**Comment by freeboub** [comment]
it  is not working end to end. let's reopen ...

**Comment by freeboub** [comment]
Is it this information that you need ?

https://developer.android.com/reference/kotlin/androidx/media3/common/Format#rotationDegrees()

**Comment by yuriiburov** [comment]
Same here.
Do you have some solution?

`"react-native": "0.72.6",`
`"react-native-video": "6.1.0"`

the link has reverted height and width
[https://bn-dev.fra1.digitaloceanspaces.com/km-tournament/uploads/rn_image_picker_lib_temp_2ee86a27_9312_4548_84af_7fd75d9ad4dd_ad8b20587a.mp4](https://bn-dev.fra1.digitaloceanspaces.com/km-tournament/uploads/rn_image_picker_lib_temp_2ee86a27_9312_4548_84af_7fd75d9ad4dd_ad8b20587a.mp4)

the size should be: `width: 720, height: 1280`
but method `onLoad` return 
`{"audioTracks": [], "canPlayFastForward": true, "canPlayReverse": true, "canPlaySlowForward": true, "canPlaySlowReverse": true, "canStepBackward": true, "canStepForward": true, "currentTime": 0, "duration": 3.899977684020996, "naturalSize": {"height": 720, "orientation": "landscape", "width": 1280}, "target": 1313, "textTracks": []}`
where in `"naturalSize": {"height": 720, "orientation": "landscape", "width": 1280}` width and height are reverted and orientation is wrong.

**Comment by freeboub** [comment]
Will be available in next version 6.1.2

**Comment by yuriiburov** [comment]
> Will be available in next version 6.1.2

it would be good, but how do you know that?
I see, that you wrote above about 6.0.0, but it doesn't work in this version(

**Comment by freeboub** [comment]
I did a first fix on 6.0.0 and a second one was merged on 6.1.1 (not 6.1.2)

**Comment by yuriiburov** [comment]
> I did a first fix on 6.0.0 and a second one was merged on 6.1.1 (not 6.1.2)

do you know when version 6.1.2 will be available to install?

**Comment by yuriiburov** [comment]
it works on 6.1.1

**Comment by yuriiburov** [comment]
@freeboub Hi, I noticed that now android has the same wrong natural size problem

width: 1280 (wrong), height: 720 (wrong), https://bn-dev.fra1.digitaloceanspaces.com/km-tournament/uploads/rn_image_picker_lib_temp_2ee86a27_9312_4548_84af_7fd75d9ad4dd_ad8b20587a.mp4

`"react-native": "0.74.1",`
`"react-native-video": "6.1.2"`

**Comment by freeboub** [comment]
I pushed I just push another fix, sorry for the inconvenience ...

**Comment by yuriiburov** [comment]
> I pushed I just push another fix, sorry for the inconvenience ...

Apperciated)
Waiting for new version 👀

**Comment by freeboub** [comment]
will be available in 6.2.0

**Comment by stee1ix** [comment]
Still happening on 6.9.0 @freeboub. Related to https://github.com/TheWidlarzGroup/react-native-video/issues/3713.
The height and width flips in videoTracks as to whats is naturalSize

```
"naturalSize": {
        "height": 1024,
        "orientation": "portrait",
        "width": 576
    },
    "videoTracks": [
        {
            "rotation": 0,
            "selected": false,
            "bitrate": 1727404,
            "trackId": "0",
            "index": 0,
            "codecs": "avc1.64001f",
            "height": 576,
            "width": 1024
        },
        {
            "rotation": 0,
            "selected": false,
            "bitrate": 853409,
            "trackId": "1",
            "index": 1,
            "codecs": "avc1.4d001e",
            "height": 360,
            "width": 640
        },
        {
            "rotation": 0,
            "selected": false,
            "bitrate": 573404,
            "trackId": "2",
            "index": 2,
            "codecs": "avc1.4d0015",
            "height": 240,
            "width": 428
        },
        {
            "rotation": 0,
            "selected": false,
            "bitrate": 388674,
            "trackId": "3",
            "index": 3,
            "codecs": "avc1.64000c",
            "height": 144,
            "width": 256
        }
    ],
    
    I see a `rotation` property in `videoTracks` of v6 which wasn't in v5.

**Comment by stee1ix** [comment]
Revering this [PR](https://github.com/TheWidlarzGroup/react-native-video/pull/4219) and creating patch, fixed the issue for me.

**Comment by freeboub** [comment]
> Revering this [PR](https://github.com/TheWidlarzGroup/react-native-video/pull/4219) and creating patch, fixed the issue for me.

Can you share a sample video please ?
