### ISSUE TITLE
[iOS] black screen after updating video source in fullscreen (controls={true})

### ISSUE THREAD

**Issue by 3vilguy** [TheWidlarzGroup/react-native-video#2102]
# Bug

Hello guys!
I've been using the lib for a while now and it keeps getting better and better. Thanks for the great work!

Unfortunatly I'm currently experiencing some issues regarding playing multiple videos (one after another) in fullscreen on iOS, when using `controls={true}`. I'm still not sure what's the recommended way of updating the source, but I found some ways of doing it by adding `key` props. That seems to be working on normal player, but not with fullscreen.
What's currently happening is:
- after video finishes I'm trying to change the uri to play the next one.
- whole screen stays black and new video is not playing in fulscreen.
- I can hear the sounds which means 2nd video is playing somewhere and after closing fullscreen I can see the other video playing in normal player.

Any hints or ideas about how to get this working appreciated.

## Platform
Which player are you experiencing the problem on:
* iOS

## Environment info

```bash
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 6.33 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: Not Found
    npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.2 => 0.63.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 4.4.5

## Steps To Reproduce

1. Go fullscreen with native controls
2. Let 1st video finish (scroll to almost end to speed up the process)

## Expected behaviour

1. Next video should start playing in full screen.

## Reproducible sample code

```js
import React, { Component } from 'react';
import {
    Dimensions,
    StyleSheet,
    View,
} from 'react-native';
import Video from 'react-native-video';

const videos = [
    'http://mirrors.standaloneinstaller.com/video-sample/grb_2.mp4',
    'http://mirrors.standaloneinstaller.com/video-sample/lion-sample.mp4',
    'http://mirrors.standaloneinstaller.com/video-sample/jellyfish-25-mbps-hd-hevc.mp4',
    'http://mirrors.standaloneinstaller.com/video-sample/DLP_PART_2_768k.mp4',
];

const { width, height } = Dimensions.get('window');

class VideoPlayer extends Component {
    constructor() {
        super();
        const startIndex = 0;

        this.state = {
            index: startIndex,
            videoUri: videos[startIndex],
        };
    };

    setNextVideo = () => {
        let i = this.state.index + 1;
        if (i > videos.length || !videos[i]) {
            i = 0;
        }
        console.log("Next vid =>", i, videos[i])
        this.setState({
            index: i,
            videoUri: videos[i],
        });
    };

    onVideoEnd = () => {
        console.log("onVideoEnd");
        // this.videoPlayer.dismissFullscreenPlayer();   // This doesn't work
        this.setNextVideo();
    }

    render() {
        return (
            <View>
                <Video
                    key={this.state.videoUri}   // Without this even NOT Full screen doesn't work
                    source={{ uri: this.state.videoUri }}
                    style={styles.videoPlayer}
                    resizeMode={'contain'}
                    controls={true}
                    onEnd={this.onVideoEnd}

                    ref={p => { this.videoPlayer = p; }}
                />
            </View>
        );
    }
};

const styles = StyleSheet.create({
    videoPlayer: {
        width: width,
        height: width * (9 / 16)
    },
});

export default VideoPlayer;
```

## Video sample
URLs with sample files are already included in the code above.

**Comment by legion-zver** [comment]
@3vilguy, I fixed it on iOS, remove key and use this path (patch-package):

**react-native-video+5.1.0-alpha8.patch**

```
diff --git a/node_modules/react-native-video/ios/Video/RCTVideo.m b/node_modules/react-native-video/ios/Video/RCTVideo.m
index 8780f48..2b0f9d9 100644
--- a/node_modules/react-native-video/ios/Video/RCTVideo.m
+++ b/node_modules/react-native-video/ios/Video/RCTVideo.m
@@ -395,7 +395,13 @@ - (void)setSrc:(NSDictionary *)source
       if (@available(iOS 10.0, *)) {
         [self setAutomaticallyWaitsToMinimizeStalling:_automaticallyWaitsToMinimizeStalling];
       }
-
+      // For support change source after create
+      if (_playerViewController != NULL) {
+        [_playerViewController setPlayer:_player];
+      }
+      if (_playerLayer != NULL) {
+        [_playerLayer setPlayer:_player];
+      }
       //Perform on next run loop, otherwise onVideoLoadStart is nil
       if (self.onVideoLoadStart) {
         id uri = [self->_source objectForKey:@"uri"];

```

**Comment by 3vilguy** [comment]
Hi @legion-zver, thanks for your time. Would be great to have it fixed.
Unfortunately I'm struggling a bit with testing it. I never used patch-package before, so I just manually updated the `RCTVideo.m` file. However after doing that and rebuilding the project the same issue still occures :(

**Comment by Tiepbm** [comment]
> [@3vilguy](https://github.com/3vilguy), I fixed it on iOS, remove key and use this path (patch-package):
> 
> **react-native-video+5.1.0-alpha8.patch**
> 
> ```
> diff --git a/node_modules/react-native-video/ios/Video/RCTVideo.m b/node_modules/react-native-video/ios/Video/RCTVideo.m
> index 8780f48..2b0f9d9 100644
> --- a/node_modules/react-native-video/ios/Video/RCTVideo.m
> +++ b/node_modules/react-native-video/ios/Video/RCTVideo.m
> @@ -395,7 +395,13 @@ - (void)setSrc:(NSDictionary *)source
>        if (@available(iOS 10.0, *)) {
>          [self setAutomaticallyWaitsToMinimizeStalling:_automaticallyWaitsToMinimizeStalling];
>        }
> -
> +      // For support change source after create
> +      if (_playerViewController != NULL) {
> +        [_playerViewController setPlayer:_player];
> +      }
> +      if (_playerLayer != NULL) {
> +        [_playerLayer setPlayer:_player];
> +      }
>        //Perform on next run loop, otherwise onVideoLoadStart is nil
>        if (self.onVideoLoadStart) {
>          id uri = [self->_source objectForKey:@"uri"];
> ```

can you fix issue on android?
