### ISSUE TITLE
[BUG]: How to fix "concurrency is only available in iOS 13.0.0 or newer"

### ISSUE THREAD

**Issue by HuuNguyen312** [TheWidlarzGroup/react-native-video#3761]
### Version

v6.0.0-rc.1

### What platforms are you having the problem on?

iOS

### Architecture

Old architecture

### What happened?

My podfile:
```
platform :ios, '13.0'
```

### Reproduction

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by KrzysztofMoch** [comment]
Did you check your iOS target version in Xcode ?

**Comment by HuuNguyen312** [comment]
@KrzysztofMoch Thanks for your response.

<img width="710" alt="image" src="https://github.com/TheWidlarzGroup/react-native-video/assets/9895294/d2e4143d-0dba-48c9-a07f-101035ff557e">
<img width="386" alt="image" src="https://github.com/TheWidlarzGroup/react-native-video/assets/9895294/8f353f39-74ab-4d85-962a-f7742b37918c">

**Comment by KrzysztofMoch** [comment]
strange... this should work, cloud you check in "Pods" (in xcode) if pods dependencies also have this set to good value ?

**Comment by freeboub** [comment]
Can you try also to force ios 13.0 as a minimum version in your podfile like with this patch: https://github.com/TheWidlarzGroup/react-native-video/commit/e34d8fe250032f3e250475f46cd3defdcd729872

**Comment by ayberkanilatsiz** [comment]
I fixed it with change Deployment iOS Deployment Target in Pods > react-native-video > Build Settings iOS Deployment Target

![Screenshot 2024-05-21 at 16 34 23](https://github.com/TheWidlarzGroup/react-native-video/assets/7476653/0d32c620-0f96-4227-a707-e1b9a2854ebc)

**Comment by freeboub** [comment]
@ayberkanilatsiz did you try the patch I proposed ?

**Comment by freeboub** [comment]
Will be addresses by: https://github.com/TheWidlarzGroup/react-native-video/pull/3814

**Comment by Mihai-github** [comment]
still not working with this version: "react-native-video": "^6.1.2",

**Comment by CarloTamburrelli** [comment]
> I fixed it with change Deployment iOS Deployment Target in Pods > react-native-video > Build Settings iOS Deployment Target
> 
> ![Screenshot 2024-05-21 at 16 34 23](https://private-user-images.githubusercontent.com/7476653/332446361-0d32c620-0f96-4227-a707-e1b9a2854ebc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NjgwMjUsIm5iZiI6MTcxNzk2NzcyNSwicGF0aCI6Ii83NDc2NjUzLzMzMjQ0NjM2MS0wZDMyYzYyMC0wZjk2LTQyMjctYTcwNy1lMWI5YTI4NTRlYmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDlUMjExNTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTJlMmVmMjFjNjVmMjk0M2EzM2UyNmIwNGZmODcyNDAzMGM0YjhhNDg4NjZhYzhhZTAwNmZjMzUyZGIyYWNhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PY342frZTqsbOkA5UriAJ6wHXootHsn6FNTT5Q0EgEQ)

thank you! it works! (my version was "react-native-video": "^6.2.0") I assume this is a hard coded solution, will there be an official solution somewhere?
