### ISSUE TITLE
[BUG]: The Ad is not playing in iOS when changing the source

### ISSUE THREAD

**Issue by MdAbubakar** [TheWidlarzGroup/react-native-video#4423]
### Version

6.10.2

### What platforms are you having the problem on?

iOS

### System Version

All iOS versions

### On what device are you experiencing the issue?

Real device

### Architecture

Old architecture

### What happened?

Actually, I want to play the mid roll ads when the current time meets the mid roll positions and I'm trying to change the source using the videoRef.current.setSource() and here I'm passing the content URL and the adTagUrl so in Android it's working fine but in iOS the content starts playing again and the ad is skipping. So I thought it is a player id or key issue so I change the Video component key manually in iOS then it is working but after changing the key it's creating a new instance of the Video component which leads the loading time. Please check the issue

### Reproduction Link

no link

### Reproduction

Step to reproduce this bug are: 

Please see my implementation you can reproduce it if not changing the key of Video component and try to change the source as I'm changing for Android,

const triggerMidRollAd = cuePoint => {
    if (!isAdRecentlyPlayedRef.current) {
      isAdRecentlyPlayedRef.current = true;
      setShowMidRollAds(true);
      setShowControls(false);
      setAdUrl(midRollAdUrl);

      if (Platform.OS === "ios") {
        setMidRollKey(prevKey => prevKey + 1);
      } else {
        videoRef?.current?.setSource({
          uri: videoURL,
          headers: {
            "Content-Type": "application/x-mpegURL",
            "User-Agent": userAgent,
          },
          ad: {
            adTagUrl: midRollAdUrl,
          },
          startPosition: Math.floor(progressRef?.current?.currentTime) * 1000,
        });
      }
      setCuePoints(prev => prev.filter(point => point !== cuePoint));
      setSkippedCuePoints(prev => prev.filter(point => point !== cuePoint));

      setTrackMarks(prev => prev.filter(mark => mark !== cuePoint));
    }
  };

 const OnReceiveAdEvent = useCallback(
    event => {
      if (event.event !== "AD_PROGRESS") {
        console.log("adEvent: ", event);
      }

      if (
        event.event === "LOADED" ||
        event.event === "CONTENT_PAUSE_REQUESTED"
      ) {
        setIsAdLoaded(true);
        setIsLoading(true);
        videoRef?.current?.resume();
        setPaused(false);
      }

      if (event.event === "STARTED" || event.event === "AD_PROGRESS") {
        setIsLoading(false);
      }

      if (event.event === "CLICK") {
        setShowFullscreen(false);
      }

      if (AD_PLAY_TYPES.includes(event.event)) {
        setIsAdPlay(true);
        zoomScale.value = 1;
      }
      if (AD_STOP_TYPES.includes(event.event)) {
        setIsAdPlay(false);
        setIsAdLoaded(false);
        setIsLoading(false);
        videoRef?.current?.resume();
        setPaused(false);
        if (showPostRollAds) {
          handleVideoEnd();
        } else if (Platform.OS === "ios" && showMidRollAds) {
          setAdUrl("");
          setMidRollKey(prevKey => prevKey - 1);
        } else if (Platform.OS === "android") {
          videoRef?.current?.setSource({
            uri: videoURL,
            headers: {
              "Content-Type": "application/x-mpegURL",
              "User-Agent": userAgent,
              user_id: userdata?.session,
              subscriber_id: userdata?.user_id,
            },
            ad: {
              adTagUrl: "",
            },
            startPosition: Math.floor(progressRef?.current?.currentTime) * 1000,
            minLoadRetryCount: 8,
            bufferConfig: {
              minBufferMs: 15000,
              maxBufferMs: 90000,
              bufferForPlaybackMs: 3000,
              bufferForPlaybackAfterRebufferMs: 10000,
              backBufferDurationMs: 120000,
              cacheSizeMB: 10,
            },
          });

          setTimeout(() => {
            setShowMidRollAds(false);
          }, 500);
        }

        const resetTimer =
          midRollPositions?.length > 0
            ? (midRollPositions[0] / 2) * 1000
            : 60000;

        setTimeout(() => {
          isAdRecentlyPlayedRef.current = false;
        }, resetTimer);
      }

      if (event.event === "PAUSED" && !paused) {
        setPaused(true);
      }

      if (event.event === "RESUMED" && paused) {
        setPaused(false);
      }
    },
    [showMidRollAds, showPostRollAds, paused],
  );

  <Video
              key={`videoPlayer${midRollKey}`}
              source={{
                uri: videoURL,
                headers: {
                  "Content-Type": "application/x-mpegURL",
                  "User-Agent": userAgent,
                },
                ad: {
                  adTagUrl: adUrl,
                },
                startPosition: videoStartPosition,
                minLoadRetryCount: 8,
                bufferConfig: {
                  minBufferMs: 15000,
                  maxBufferMs: 90000,
                  bufferForPlaybackMs: 3000,
                  bufferForPlaybackAfterRebufferMs: 10000,
                  backBufferDurationMs: 120000,
                  cacheSizeMB: 10,
                },
              }}
              onReceiveAdEvent={OnReceiveAdEvent}
              shutterColor="transparent"
              viewType={ViewType.SURFACE_SECURE}
              style={[
                styles.video,
                {
                  zIndex: 1,
                },
              ]}
              resizeMode={
                isAdPlay
                  ? ResizeMode.CONTAIN
                  : showFullscreen && fitToScreen
                  ? ResizeMode.COVER
                  : isPipActive
                  ? ResizeMode.COVER
                  : ResizeMode.CONTAIN
              }
              ref={videoRef}
              onProgress={handleVideoProgress}
              rate={selectedSpeed}
              playInBackground={false}
              enterPictureInPictureOnLeave={!isScreenRecording}
              onPictureInPictureStatusChanged={({ isActive }) => {
                console.log("isActive: ", isActive);
                setIsPipActive(isActive);
                pipModecallback(isActive);
                if (isActive) {
                  setShowControls(false);
                  if (!playRef.current.paused) {
                    if (isCasting) {
                      client?.play();
                    }
                    setPaused(false);
                  }
                } else {
                  setActiveCall(false);
                  BackgroundTimer.setTimeout(() => {
                    if (AppState.currentState === "background") {
                      client?.stop();
                      playRef.current.paused = true;
                      setPaused(true);
                    }
                  }, 700);
                }
              }}
              onRestoreUserInterfaceForPictureInPictureStop={() => {
                if (Platform.OS === "ios" && videoRef.current) {
                  videoRef?.current?.restoreUserInterfaceForPictureInPictureStopCompleted(
                    true,
                  );
                }
              }}
              poster={
                thumbnailImage && showPoster
                  ? {
                      source: { uri: thumbnailImage },
                      resizeMode: screenWidth >= 800 ? "cover" : "contain",
                    }
                  : undefined
              }
              paused={isCasting ? true : isScreenRecording ? true : paused}
              ignoreSilentSwitch={"ignore"}
              playWhenInactive={true}
              onLoadStart={() => {
                setIsLoading(true);
              }}
              onLoad={handleVideoLoad}
              maxBitRate={getMaxBitRate(selectedResolution)}
              onAudioTracks={audioTracks => {
                // console.log("audioTracks: ", audioTracks);
                if (audioTracks?.audioTracks?.length > 1) {
                  setShowAudio(true);
                  const languages = audioTracks?.audioTracks?.map(
                    item => item.title,
                  );
                  setAvailableAudio(languages);
                } else {
                  setShowAudio(false);
                }
              }}
              onTextTracks={subtitle => {
                if (
                  subtitle.textTracks.length > 0 &&
                  (subtitle.textTracks[0]?.language !== "" ||
                    subtitle.textTracks[0]?.title !== "")
                ) {
                  setShowSubtitle(true);
                  const languages = subtitle?.textTracks?.map(
                    item => item.language,
                  );
                  setAvailableSubtitles(languages);
                } else {
                  setShowSubtitle(false);
                }
              }}
              selectedAudioTrack={{
                type: SelectedTrackType.INDEX,
                value: selectedAudio
                  ? availableAudio?.indexOf(selectedAudio)
                  : 0,
              }}
              selectedTextTrack={{
                type:
                  showSubtitle && selectedSubtitle !== ""
                    ? SelectedTrackType.INDEX
                    : SelectedTrackType.DISABLED,
                value: availableSubtitles?.indexOf(selectedSubtitle),
              }}
              subtitleStyle={{
                paddingBottom: showFullscreen ? 70 : 10,
                fontSize: showFullscreen ? 16 : 13,
                subtitlesFollowVideo: false,
              }}
              volume={volume}
              shouldPlay={true}
              onEnd={() => {
                console.log("content playback completed");
                if (postRollUrl) {
                  setShowPostRollAds(true);
                  if (Platform.OS === "ios") {
                    setMidRollKey(prevKey => prevKey + 1);
                    setAdUrl(postRollUrl);
                    setPostRollUrl("");
                  } else {
                    videoRef.current?.setSource({
                      uri: videoURL,
                      ad: {
                        adTagUrl: postRollUrl,
                      },
                      startPosition:
                        Math.floor(progressRef?.current?.seekableDuration - 1) *
                        1000,
                      minLoadRetryCount: 8,
                      bufferConfig: {
                        minBufferMs: 15000,
                        maxBufferMs: 90000,
                        bufferForPlaybackMs: 3000,
                        bufferForPlaybackAfterRebufferMs: 10000,
                        backBufferDurationMs: 120000,
                        cacheSizeMB: 10,
                      },
                    });
                  }
                } else {
                  handleVideoEnd();
                }
              }}
              onError={error => {
                console.log("playback error: ", error);
                if (contentType === "live" || contentType === "livetv") {
                  setTimeout(() => {
                    setPaused(true);
                    playRef.current.paused = true;
                    setShowPlaybackError(true);
                    setVideoURL("");
                  }, 5000);
                } else {
                  setPaused(true);
                  playRef.current.paused = true;
                  setShowPlaybackError(true);
                  setVideoURL("");
                }
                setIsAdPlay(false);
                setIsAdLoaded(false);
              }}
              onBuffer={({ isBuffering }) => {
                if (isCasting) {
                  setIsLoading(false);
                } else {
                  setIsLoading(isBuffering);
                }
              }}
              onAudioFocusChanged={event => {
                if (!event.hasAudioFocus) {
                  setPaused(true);
                  playRef.current.paused = true;
                  setActiveCall(true);
                } else if (AppState.currentState === "active") {
                  setPaused(false);
                  playRef.current.paused = false;
                  setActiveCall(false);
                } else if (isPipActive) {
                  setPaused(false);
                  playRef.current.paused = false;
                  setActiveCall(false);
                }
              }}
              onPlaybackStateChanged={event => {
                if (!event.isSeeking && isPipActive) {
                  setPaused(!event.isPlaying);
                  playRef.current.paused = !event.isPlaying;
                }
                if (event.isPlaying) {
                  setActiveCall(false);
                }
              }}
            />

**Comment by freeboub** [comment]
Why don't you pass directly midRollAdUrl at playback start ? (it is the package expectation)
Did you try to pass:       `startPosition: Math.floor(progressRef?.current?.currentTime - 20000) * 1000,`to be sure to be before the CUE point ?

**Comment by MdAbubakar** [comment]
Thank you @freeboub for your response as you suggested to pass the startPosition 20 seconds before the cue points as I checked this one also but after this the content starting 20 seconds before the current time but my problem is the setSource method it should work as it's working in Android, whenever I'm changing the source with the adTagUrl the ad is playing but in iOS the content starts playing and the ad is skipping so I implemented the key increment/decrement logic as you can see in my codes so can you please check on your side as multiple instance of the Video component is being created after increasing the key which is not an ideal solution. Please check this scenario

Thanks in advance

**Comment by MdAbubakar** [comment]
@freeboub Sir, any update on it as it should work same as Android when changing the source using the setSource() method along with the adTagUrl and the when the ad is loading there's a blank screen clearly visible.

@freeboub Sir, please look into it

**Comment by freeboub** [comment]
unfortunately, I don't have enough time to debug / develop this package... I still continue to review and merge PR, but I must put investigation on this package in low priority ...

**Comment by MdAbubakar** [comment]
@freeboub now I'm able to play the mid rolls and avoiding multiple video reloads by setting the videoRef to null and then changing the key of the video component now it's working as expected,

I'm pasting my implementation here can you please review it and confirm is it correct:

 const triggerMidRollAd = cuePoint => {
    setShowMidRollAds(true);
    setShowControls(false);

    if (Platform.OS === "ios") {
      videoRef.current = null;
      setPlayerKey(prevKey => prevKey + 1);
      setAdUrl(midRollAdUrl);
      setVideoStartPosition(
        Math.floor(progressRef?.current?.currentTime) * 1000,
      );
    } else {
      videoRef?.current?.setSource({
        uri: videoURL,
        headers: {
          "Content-Type": "application/x-mpegURL",
          "User-Agent": userAgent,
          user_id: userdata?.session,
          subscriber_id: userdata?.user_id,
        },
        ad: {
          adTagUrl: midRollAdUrl,
        },
        startPosition: Math.floor(progressRef?.current?.currentTime) * 1000,
        minLoadRetryCount: 8,
        bufferConfig: {
          minBufferMs: 15000,
          maxBufferMs: 90000,
          bufferForPlaybackMs: 3000,
          bufferForPlaybackAfterRebufferMs: 10000,
          backBufferDurationMs: 120000,
          cacheSizeMB: 0,
          live: {
            targetOffsetMs: 500,
          },
        },
      });
    }
    setCuePoints(prev => prev?.filter(point => point !== cuePoint));
    setSkippedCuePoints(prev => prev?.filter(point => point !== cuePoint));

    setTrackMarks(prev => prev?.filter(mark => mark !== cuePoint));
    skippedAd.current = 0;
  };

 const handleVideoEnd = () => {
    setPostRollUrl("");
    setShowPoster(true);
    if (preview) {
      Orientation.lockToPortrait();
      setShowFullscreen(false);
      isPipActive ? fullscreenCallback(true) : fullscreenCallback(false);
    }
    onEnd(count);
    if (!isNextItem) {
      setShowControls(true);
      setCanReplay(true);
      setPlaybackCompleted(true);
      triggeredEvent.current.pbEnd = true;
      triggeredEvent.current.pbStart = false;
    }
    setTimeout(() => {
      setShowPostRollAds(false);
    }, 500);
  };

  const OnReceiveAdEvent = useCallback(
    event => {
      if (event.event !== "AD_PROGRESS") {
        console.log("adEvent: ", event);
      }

      if (
        event.event === "LOADED" ||
        event.event === "CONTENT_PAUSE_REQUESTED"
      ) {
        setIsAdLoaded(true);
        setIsLoading(true);
        videoRef?.current?.resume();
        setPaused(false);
      }

      if (event.event === "STARTED" || event.event === "AD_PROGRESS") {
        setIsLoading(false);
      }

      if (event.event === "CLICK") {
        setShowFullscreen(false);
      }

      if (AD_PLAY_TYPES.includes(event.event)) {
        setIsAdPlay(true);
        zoomScale.value = 1;
        if (isCasting) {
          client?.stop();
        }
      }
      if (AD_STOP_TYPES.includes(event.event)) {
        setIsAdPlay(false);
        setIsAdLoaded(false);
        setIsLoading(false);
        videoRef?.current?.resume();
        setPaused(false);
        if (showPostRollAds) {
          handleVideoEnd();
        } else {
          setTimeout(() => {
            setShowMidRollAds(false);
          }, 500);
        }
      }

      if (event.event === "PAUSED" && !paused) {
        setPaused(true);
      }

      if (event.event === "RESUMED" && paused) {
        setPaused(false);
      }
    },
    [showMidRollAds, showPostRollAds, paused, isCasting],
  );

**Comment by freeboub** [comment]
Thank you for the share!
