### ISSUE TITLE
RCTViewManager.h not found

### ISSUE THREAD

**Issue by moerabaya** [TheWidlarzGroup/react-native-video#457]
Here's the error:
/usr/local/lib/node_modules/react-native-video/RCTVideoManager.h:1:9: fatal error: 'RCTViewManager.h' file not found
#import "RCTViewManager.h"

**Comment by hellogerard** [comment]
@moerabaya This is duplicated by several other issues, and fixed in `master` by #381.  It should drop in the next release. Can you close this issue, please?

**Comment by moerabaya** [comment]
@hellogerard Is there's a fix for it, or I have to wait for the next release?

**Comment by hellogerard** [comment]
@moerabaya You will have to wait for the next release. In the meantime, you can install the `master` branch directly to your project.

`npm i -S git://github.com/react-native-community/react-native-video.git`

**Comment by jussirantala** [comment]
I'm using react-native-video 4.4.0 and react-native 0.57.8 and I get this same error. I've tried to install with cocoapods and also tried manual linking (https://facebook.github.io/react-native/docs/linking-libraries-ios).

**Comment by cinder92** [comment]
this error still hapening in RN 0.59 with plugin version 4.4.0

Not working either with Cocoa Pods, Header Search path, Dragginn into Linked frameworks, react-native-link bah

**Comment by rzrobert** [comment]
I think this error because of link react-native-video, link with React (0.11.0)。

You should remove this link:

- react-native unlink react-native-video
- open your xcode:File>Workspace Setting>Build System>Legacy Build System
<img width="534" alt="QQ20190529-172159@2x" src="https://user-images.githubusercontent.com/16103572/58545806-9d468480-8236-11e9-9a5f-46f87384c2c3.png">

- Libraries: add RCTVideo.xcodeproj
<img width="277" alt="QQ20190529-172134@2x" src="https://user-images.githubusercontent.com/16103572/58545811-a20b3880-8236-11e9-95a1-834beff2f220.png">

- Linked Frameworks and Libraries -> libRCTVideo.a 
<img width="605" alt="QQ20190529-172216@2x" src="https://user-images.githubusercontent.com/16103572/58545822-a59ebf80-8236-11e9-9643-7e1a5cc0f3d9.png">

*hope it will work for you.*

**Comment by Balasnest** [comment]
what is the latest version works for react native 0.57.2?  Its working with 3.2.1 Version. But there is some issue with remote video. So I am planning to upgrade but build is failing.

Anybody made it work with latest version **4.0.0 and above**?

**Comment by ironworkshop** [comment]
> I think this error because of link react-native-video, link with React (0.11.0)。
> 
> You should remove this link:
> 
> * react-native unlink react-native-video
> * open your xcode:File>Workspace Setting>Build System>Legacy Build System
> 
> <img alt="QQ20190529-172159@2x" width="534" src="https://user-images.githubusercontent.com/16103572/58545806-9d468480-8236-11e9-9a5f-46f87384c2c3.png">
> 
> * Libraries: add RCTVideo.xcodeproj
> 
> <img alt="QQ20190529-172134@2x" width="277" src="https://user-images.githubusercontent.com/16103572/58545811-a20b3880-8236-11e9-95a1-834beff2f220.png">
> 
> * Linked Frameworks and Libraries -> libRCTVideo.a
> 
> <img alt="QQ20190529-172216@2x" width="605" src="https://user-images.githubusercontent.com/16103572/58545822-a59ebf80-8236-11e9-9643-7e1a5cc0f3d9.png">
> 
> _hope it will work for you._

This was the fix for me, thank you so much! I was battling with lots of errors these steps fixed it for me. For others this is using RN 0.59.3 & React-native-video 4.4.1
