### ISSUE TITLE
[BUG]: Thread 1: "-[RCTView setNitroId:]: unrecognized selector sent to instance 0x30c9705e0"

### ISSUE THREAD

**Issue by 8699921209** [TheWidlarzGroup/react-native-video#4600]
### Version

7.0.0-alpha.1

### What platforms are you having the problem on?

iOS

### System Version

iphone 16 pro

### On what device are you experiencing the issue?

Simulator

### Architecture

New architecture with interop layer

### What happened?

<img width="1440" height="900" alt="Image" src="https://github.com/user-attachments/assets/1ec44588-52d9-4fcd-b5bf-3ac486efb806" />

🐛 iOS Crash: -[RCTView setNetInfoId:]: unrecognized selector with react-native-video@7.0.0-alpha.1

Hi everyone,
I'm running into a crash on iOS only when using react-native-video. Everything works perfectly on Android. Here's my setup:

📦 Dependencies:
react-native: 0.80.1

react-native-video: ^7.0.0-alpha.1
react-native-nitro-modules: ^0.26.3

💥 Crash Details:
On launch, the app crashes with the following error:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException',
reason: '-[RCTView setNetInfoId:]: unrecognized selector sent to instance'
Xcode trace:

-[RCTComponentData createPropBlock:isShadowView:] -> Thread 1: "-[RCTView setNetInfoId:]: unrecognized selector"
🔍 Notes:

I'm not manually passing any netInfoId prop anywhere.
This error seems to be triggered inside the native RCTComponentData class.
Possibly related to react-native-video or nitro-modules generating an invalid or unintended prop setter?
Android works flawlessly with the same codebase.

📱 Environment:
Simulator: iPhone 16 Pro

iOS 18.5
macOS Sonoma
Xcode Version: 16.4 (16F6)

Any suggestions or help would be much appreciated!
If anyone else is using react-native-video@7.0.0-alpha.1 with NitroModules on iOS, please let me know if you’ve faced similar issues or found a workaround.

Thanks! 🙏

### Reproduction Link

repository link

### Reproduction

Step to reproduce this bug are:

**Comment by KrzysztofMoch** [comment]
Hey @8699921209, can you post reproduction? I haven't seen this error before. Thanks

**Comment by KrzysztofMoch** [comment]
Hey @8699921209, this should be fixed by this PR #4616

**Comment by 8699921209** [comment]
Hi @KrzysztofMoch 👋
Thank you for this PR — it looks like a really helpful fix!

I tried applying these changes in my own setup (React Native 0.80 with New Architecture enabled), but I couldn't get it to work properly — the app still crashes when trying to render the

Could you please guide me step-by-step on how to properly test this fix in a fresh or existing app?
I'm not sure if I'm missing some configuration related to codegen or third-party component registration.

Thanks in advance for your help! 🙏

**Comment by KrzysztofMoch** [comment]
Okay, let me merge release #4616, so you can update easily update package and test it

**Comment by KrzysztofMoch** [comment]
I have released it, and tested it and it works - I will close this, but feel free to ping me here if you have still this issue
